pipeline {
    agent any  // Runs on any available agent

    environment {
        MAVEN_HOME = "/usr/share/maven"  // Set Maven path if required
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/PavanKalyan96Dev/SpringBootJenkins'
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean package'
            }
        }

        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploying application..."
                // Add deployment commands here
            }
        }
    }
}
